Match user space up with kernel module name change
Signed-off-by: Mark Harvey <markh794@gmail.com>

diff --git a/usr/build_library_config b/usr/build_library_config
--- a/usr/build_library_config
+++ b/usr/build_library_config
@@ -58,10 +58,12 @@ if [ ! -f $DEVICE_CONF ]; then
 fi
 
 # Test for new interface to dynamically add logical units.
-if [ ! -f /sys/bus/pseudo/drivers/mhvtl/add_lu ]; then
-	echo "Sorry, Can't continue - No kernel module loaded or out of date ??"
-	echo "Please visit http://sites.google.com/site/linuxvtl2/"
-	exit 1
+if [ ! -f /sys/bus/pseudo9/drivers/mhvtl/add_lu ]; then
+	if [ ! -f /sys/bus/pseudo/drivers/mhvtl/add_lu ]; then
+		echo "Sorry, Can't continue - No kernel module loaded or out of date ??"
+		echo "Please visit http://sites.google.com/site/linuxvtl2/"
+		exit 1
+	fi
 fi
 
 # First we need to setup & configure drives.
