Earlier kernels do not have the oom killer setting. Ignore oom return.
Due to older 2.6 kernels not having the ability to 'tune' oom killer, I
ignore the return code.
- Made the rc script a little more robust by checking return code of
  build_library_config

diff --git a/vtl b/vtl
--- a/vtl
+++ b/vtl
@@ -49,7 +49,7 @@ case "$1" in
 		echo "Incorrect kernel module for these daemons."
 		echo "Need at least 0.12.10"
 		exit 1
-	elif [ "X$vtlVersion" != "X11" ]; then
+	elif [ "$vtlVersion" -lt "11" ]; then
 		echo "Incorrect kernel module for these daemons."
 		echo "Need at least 0.12.11 and $vtlVersion is loaded."
 		exit 1
@@ -136,6 +136,10 @@ CONF_SAMPLE
 	# Build Library config - No. of drives & serial Nos etc..
 	# This also loads each tape daemon.
 	build_library_config $USER
+	if [ $? != 0 ]; then
+		echo "build_library_config failed.."
+		exit 1
+	fi
 
 	# Now correct file permissions..
 	chown -R $USER:$USER /opt/vtl
