fix : added $ in front of MHVTL_HOME_PATH variable in order to display the path parameter correctly in the error

diff --git a/etc/generate_device_conf.in b/etc/generate_device_conf.in
--- a/etc/generate_device_conf.in
+++ b/etc/generate_device_conf.in
@@ -440,7 +440,7 @@ fi
 # (for use in the device.conf we generate)
 if [[ ! -d "$MHVTL_HOME_PATH" ]] ; then
 	if [[ -z "$OVERRIDE" ]] ; then
-		echo "error: MHVTL_HOME_PATH not a directory" 1>&2
+		echo "error: $MHVTL_HOME_PATH not a directory" 1>&2
 		usage
 		exit 1
 	fi
