Make rc script a litte more robust.
Re-order some basic tests for config file before they
are being used. This way they can be sourced/parsed
with the knowledge they exist and have correct permissions.

Signed-off-by: Mark Harvey <mark_harvey@symantec.com>

diff --git a/etc/vtl b/etc/vtl
--- a/etc/vtl
+++ b/etc/vtl
@@ -8,7 +8,7 @@
 #
 # /etc/init.d/vtl
 #
-# Script to start vtl kernel module & vxtape userspace daemon
+# Script to start vtl kernel module & vtltape userspace daemon
 #
 # Virtual tape & library system
 #
@@ -20,10 +20,11 @@
 # Required-Stop:
 # Default-Start:  2 3 5
 # Default-Stop: 0 1 6
-# Description:    Script to start/stop vtl kernel modules & vxtape userspace daemons
+# Description:    Script to start/stop vtl kernel modules & vtltape userspace daemons
 ### END INIT INFO
 
 USER=vtl
+DEFAULT_FW=5400
 
 OPTIONS=
 # OPTIONS=" -v"
@@ -35,61 +36,17 @@ if [ -f /etc/rc.status ]; then
 	rc_reset
 fi
 
-if [ -f /etc/vtl/vtl.conf ]; then
-	. /etc/vtl/vtl.conf
+if [ -x /usr/bin/lsscsi ]; then
+	LSSCSI=/usr/bin/lsscsi
+elif [ -x /bin/lsscsi ]; then
+	LSSCSI=/bin/lsscsi
 fi
 
-case "$1" in
-    start)
-	load_vtl=`grep " vtl$" /proc/devices|awk '{print $2}'`
-	if [ "X$load_vtl" == "X" ]; then
-        	echo "Initializing vtl kernel module"
-		modprobe vtl
-		sleep 1
-		echo
-	fi
+# Create a 'vtl.conf' if it does not exist...
+if [ ! -f /etc/vtl/vtl.conf ]; then
 
-	hba=`ls /proc/scsi/vtl|tail -1`
-	if [ "X$hba" == "X" ]; then
-		echo "Incorrect (or no) kernel module loaded for these daemons."
-		echo "Need vtl kernel module version later then 0.12.12"
-		echo "Please see http://linuxvtl.googlepages.com"
-		exit 1
-	fi
-	vtlMidVersion=`grep version /proc/scsi/vtl/$hba 2> /dev/null|awk '{print $5}'|awk -F. '{print $2}'`
-	if [ $vtlMidVersion -lt 14 ]; then
-		vtlMinVersion=`grep version /proc/scsi/vtl/$hba 2> /dev/null|awk '{print $5}'|awk -F. '{print $3}'`
-		if [ $vtlMinVersion -lt 20 ]; then
-			echo "Incorrect kernel module for these daemons."
-			echo "Need at least 0.12.20 and 0.12.$vtlMinVersion is loaded."
-			echo "Please see http://linuxvtl.googlepages.com"
-			exit 1
-		fi
-		echo "Note: kernel version 0.14 is available."
-		echo "Please see http://linuxvtl.googlepages.com"
-	fi
-
-	make_vtl_devices $USER > /dev/null
-
-	# Make the kernel driver quieter...
-	if [ "X$VTL_DEBUG" != "X" ]; then
-		echo $VTL_DEBUG > /sys/bus/pseudo/drivers/vtl/opts
-	fi
-
-	# Load sg driver if not already loaded..
-	sg=`grep " sg$" /proc/devices | awk '{print $2}'`
-	if [ "X$sg" == "X" ]; then
-		/sbin/modprobe sg
-		sleep 1
-	fi
-
-	if [ ! -f /etc/vtl/vtl.conf ]; then
-		echo
-		echo "Could not locate /etc/vtl/vtl.conf"
-		echo
-		echo Creating a default one.
-		mkdir -p /etc/vtl
-		cat > /etc/vtl/vtl.conf << VTL_CONF
+mkdir -p /etc/vtl
+cat > /etc/vtl/vtl.conf << VTL_CONF
 
 # If vtl kernel module > 0.12.14, then we have the ability to either bring
 # the vtl up with all the same type of drive or mixed drive combo.
@@ -107,7 +64,7 @@ SERIAL_PREFIX=XYZ
 SSC_BUFFER_SZ=262144
 
 # Pre-set firmware version returned from INQUIRY.
-FIRMWARE=5400
+FIRMWARE=$DEFAULT_FW
 
 # Default media capacity (500 M)
 CAPACITY=500
@@ -118,16 +75,28 @@ VERBOSE=0
 # Set kernel module debuging [0|1]
 VTL_DEBUG=0
 VTL_CONF
-	fi
+fi
 
-	if [ ! -f /etc/vtl/library_contents ]; then
-		echo
-		echo "Could not locate library config file: /etc/vtl/library_contents"
-		echo
-		echo "Creating a default one"
-		echo "Please stop vtl & edit /etc/vtl/library_contents to suit your requirements"
-		mkdir -p /etc/vtl
-		cat > /etc/vtl/library_contents << CONF_SAMPLE
+. /etc/vtl/vtl.conf
+
+# Earlier versions of vtl.conf may not contain the 'FIRMWARE' string.
+# Update if nessessary..
+EXIST=`grep FIRMWARE /etc/vtl/vtl.conf|wc -l`
+if [ $EXIST -eq 0 ]; then
+	FIRMWARE=$DEFAULT_FW
+	echo "" >> /etc/vtl/vtl.conf
+	echo "# Default vtl firmware" >> /etc/vtl/vtl.conf
+	echo FIRMWARE=$DEFAULT_FW >> /etc/vtl/vtl.conf
+fi
+
+# Now check for for 'library_contents'
+if [ ! -f /etc/vtl/library_contents ]; then
+	echo
+	echo "Could not locate library config file: /etc/vtl/library_contents"
+	echo "Creating a default one"
+	echo "Please stop vtl & edit /etc/vtl/library_contents to suit your requirements"
+	mkdir -p /etc/vtl
+	cat > /etc/vtl/library_contents << CONF_SAMPLE
 Drive 1: XYZZY_1
 Drive 2: XYZZY_2
 Drive 3: XYZZY_3
@@ -178,15 +147,68 @@ Slot 31: CLN001L1
 Slot 32: CLN002L1
 Slot 33: CLN003L1
 CONF_SAMPLE
-		chmod 750 /etc/vtl
-		touch /etc/vtl/vxlib.conf
-		chown -R $USER:$USER /etc/vtl /dev/vtl[0-9]
-		mkdir -p /opt/vtl
-		chmod 770 /opt/vtl
+fi
+
+case "$1" in
+    start)
+	load_vtl=`grep " vtl$" /proc/devices|awk '{print $2}'`
+	if [ "X$load_vtl" == "X" ]; then
+        	echo "Initializing vtl kernel module"
+		modprobe vtl set_firmware=0x$FIRMWARE
+		# Virtual env - can take a few more seconds for things to load & setup..
+		DELAY=`$LSSCSI|grep VMware|wc -l`
+		if [ $DELAY -gt 0 ]; then
+			sleep 3
+		else
+			sleep 1
+		fi
+		echo
 	fi
 
+	hba=`ls /proc/scsi/vtl|tail -1`
+	if [ "X$hba" == "X" ]; then
+		echo "Incorrect (or no) kernel module loaded for these daemons."
+		echo "Need vtl kernel module version later then 0.12.12"
+		echo "Please see http://linuxvtl.googlepages.com"
+		exit 1
+	fi
+	vtlMidVersion=`grep version /proc/scsi/vtl/$hba 2> /dev/null|awk '{print $5}'|awk -F. '{print $2}'`
+	if [ $vtlMidVersion -lt 14 ]; then
+		vtlMinVersion=`grep version /proc/scsi/vtl/$hba 2> /dev/null|awk '{print $5}'|awk -F. '{print $3}'`
+		if [ $vtlMinVersion -lt 20 ]; then
+			echo "Incorrect kernel module for these daemons."
+			echo "Need at least 0.12.20 and 0.12.$vtlMinVersion is loaded."
+			echo "Please see http://linuxvtl.googlepages.com"
+			exit 1
+		fi
+		echo "Note: kernel version 0.14 is available."
+		echo "Please see http://linuxvtl.googlepages.com"
+	fi
+
+	# Load sg driver if not already loaded..
+	sg=`grep " sg$" /proc/devices | awk '{print $2}'`
+	if [ "X$sg" == "X" ]; then
+		/sbin/modprobe sg
+		sleep 1
+	fi
+
+	chmod 750 /etc/vtl
+	if [ ! -f /etc/vtl/vxlib.conf ]; then
+		touch /etc/vtl/vxlib.conf
+	fi
+	chown -R $USER:$USER /etc/vtl
+	chmod 770 /opt/vtl
+
+	# creating devices
+	make_vtl_devices $USER > /dev/null
+
 	# Now correct file permissions..
-	chown -R $USER:$USER /opt/vtl
+	chown -R $USER:$USER /opt/vtl /dev/vtl[0-9]
+
+	# Set verbosity of kernel driver
+	if [ "X$VTL_DEBUG" != "X" ]; then
+		echo $VTL_DEBUG > /sys/bus/pseudo/drivers/vtl/opts
+	fi
 
 	# Build Library config - No. of drives & serial Nos etc..
 	# This also loads each tape daemon.
@@ -204,12 +226,12 @@ CONF_SAMPLE
 	fi
 	;;
     stop)
-        echo "shutdown of vxtape daemons"
+        echo "shutdown of mhvtl"
 	for a in `ps -ef|grep ^vtl | grep "\-q"|awk '{print $10}'`
 	do
 		echo "   Sending exit to $a"
 		vtlcmd $a exit
-		usleep 100
+		usleep 100 > /dev/null 2>&1 /dev/null
 	done
 
 	# Send library daemon exit msg..
@@ -226,7 +248,7 @@ CONF_SAMPLE
 	do
 		echo "   Sending exit to $a"
 		vtlcmd $a exit
-		usleep 100
+		usleep 100 > /dev/null 2>&1 /dev/null
 	done
 
 	# Send library daemon exit msg..
